### ISSUE TITLE
Promise Bug in both `ItemAction.js` and `ProjectAction.js`

### ISSUE THREAD

**Issue by builtbylane** [builtbylane/donda-mood-board#40]
you'll see it in your server console (`node -v 6.9.1`)

```
(node:24907) Warning: a promise was created in a handler at [$path]/donda-mood-board/controllers/itemsApi.js:171:11 but was not returned from it, see http://goo.gl/rRqMUw
    at Promise.then (/Users/lg/WORK/DB/kanyewest.com/donda-mood-board/node_modules/bluebird/js/release/promise.js:124:17)

```

**Comment by roomnoise** [comment]
call 'return null;' for now on under line 171

**Comment by builtbylane** [comment]
that worked

**Comment by roomnoise** [comment]
fyi, I think is due to the fact we're using the function as middleware.  I'll make a note about it.
